Add isatty() to ColoredStream
Some versions of pip expect sys.stdout to implement isatty().

This change prevents: "AttributeError: 'ColoredStream' object has no attribute 'isatty'"